#!/bin/bash
cat	sha1.js \
	notesoup.js soupnote.js notesoup-ui-ext.js notesoup-ui-commandbar.js notesoup-ui-marquee.js \
	> miso-in.js
ls -als miso*.js
java -jar ~/Downloads/custom_rhino.jar -c miso-in.js > miso-out.js
cat ../LICENSE miso-out.js > miso.js
rm miso-in.js
rm miso-out.js
rm ../js/miso.js
cp miso.js ../js/
gzip miso.js
touch miso.js.gz
rm ../js/miso.js.gz
mv miso.js.gz ../js/
ls -als ../js/

#rm `find . -name .DS_Store`

